#!/usr/bin/env bash
#
# ====== ONE-LINERS (curl-from-GitHub direct) =================================
#
#  Default install — checks SOCKS5 at 127.0.0.1:1080 every minute by
#  curl'ing https://www.google.com through it; on 2 consecutive failures
#  runs 'systemctl restart paqet':
#
#    curl -fsSL https://raw.githubusercontent.com/gitpoemer/paqet/optimize/install-socks-watchdog.sh | sudo bash
#
#  Custom recovery command (e.g. restart something else):
#
#    curl -fsSL https://raw.githubusercontent.com/gitpoemer/paqet/optimize/install-socks-watchdog.sh \
#      | sudo RECOVERY_CMD='systemctl restart paqet xray' bash
#
#  Tweak everything:
#
#    curl -fsSL https://raw.githubusercontent.com/gitpoemer/paqet/optimize/install-socks-watchdog.sh \
#      | sudo SOCKS_HOST=127.0.0.1 SOCKS_PORT=1080 \
#             CHECK_URL=https://www.cloudflare.com CHECK_INTERVAL=2min \
#             FAIL_THRESHOLD=3 RECOVERY_CMD='systemctl restart paqet' bash
#
#  Uninstall:
#
#    sudo systemctl disable --now paqet-socks-watchdog.timer
#    sudo rm -f /etc/systemd/system/paqet-socks-watchdog.{service,timer} \
#               /usr/local/sbin/paqet-socks-watchdog.sh
#    sudo rm -rf /var/lib/paqet-socks-watchdog
#    sudo systemctl daemon-reload
#
#  All optional env vars (defaults shown):
#    SOCKS_HOST=127.0.0.1
#    SOCKS_PORT=1080
#    CHECK_URL=https://www.google.com    # site fetched through the SOCKS
#    CHECK_INTERVAL=1min                 # systemd OnUnitActiveSec format
#    FAIL_THRESHOLD=2                    # consecutive failures before recovery
#    CONNECT_TIMEOUT=5                   # curl --connect-timeout (seconds)
#    MAX_TIME=10                         # curl --max-time         (seconds)
#    RECOVERY_CMD='systemctl restart paqet'   # shell command on N-th failure
#
#  Idempotent: re-running just updates the unit files and check script in
#  place. No state is lost. systemd's daemon-reload picks up changes.
#
# =============================================================================

set -euo pipefail

# ---------------------------------------------------------------------------
# Tunables (all overridable via environment)
# ---------------------------------------------------------------------------
SOCKS_HOST="${SOCKS_HOST:-127.0.0.1}"
SOCKS_PORT="${SOCKS_PORT:-1080}"
CHECK_URL="${CHECK_URL:-https://www.google.com}"
CHECK_INTERVAL="${CHECK_INTERVAL:-1min}"
FAIL_THRESHOLD="${FAIL_THRESHOLD:-2}"
CONNECT_TIMEOUT="${CONNECT_TIMEOUT:-5}"
MAX_TIME="${MAX_TIME:-10}"
RECOVERY_CMD="${RECOVERY_CMD:-systemctl restart paqet}"

# Paths
SCRIPT_PATH="/usr/local/sbin/paqet-socks-watchdog.sh"
SERVICE_PATH="/etc/systemd/system/paqet-socks-watchdog.service"
TIMER_PATH="/etc/systemd/system/paqet-socks-watchdog.timer"
STATE_DIR="/var/lib/paqet-socks-watchdog"
STATE_FILE="$STATE_DIR/fail_count"

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------
log()  { printf '\033[1;34m[watchdog-install]\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33m[warn]\033[0m              %s\n' "$*" >&2; }
err()  { printf '\033[1;31m[err]\033[0m               %s\n' "$*" >&2; }
die()  { err "$*"; exit 1; }

require_root() {
  [[ $EUID -eq 0 ]] || die "must be run as root (or via sudo)"
}

require_cmd() {
  command -v "$1" >/dev/null 2>&1 || die "missing required command: $1 (install via apt/dnf/apk)"
}

# Validate input early so a typo in env doesn't write a broken service.
if ! [[ "$SOCKS_PORT" =~ ^[0-9]+$ ]] || (( SOCKS_PORT < 1 || SOCKS_PORT > 65535 )); then
  die "SOCKS_PORT must be a number 1..65535 (got: $SOCKS_PORT)"
fi
if ! [[ "$FAIL_THRESHOLD" =~ ^[0-9]+$ ]] || (( FAIL_THRESHOLD < 1 )); then
  die "FAIL_THRESHOLD must be a positive integer (got: $FAIL_THRESHOLD)"
fi
if ! [[ "$CONNECT_TIMEOUT" =~ ^[0-9]+$ ]]; then
  die "CONNECT_TIMEOUT must be an integer (got: $CONNECT_TIMEOUT)"
fi
if ! [[ "$MAX_TIME" =~ ^[0-9]+$ ]]; then
  die "MAX_TIME must be an integer (got: $MAX_TIME)"
fi

# ---------------------------------------------------------------------------
# Step 1: write the check script
# ---------------------------------------------------------------------------
write_check_script() {
  log "writing check script to $SCRIPT_PATH"
  install -d -m 755 "$STATE_DIR"

  # Use heredoc with escaping so the running script captures the
  # install-time values. Each run reads the values baked in, plus the
  # state file for the running fail counter.
  cat > "$SCRIPT_PATH" <<EOF
#!/usr/bin/env bash
#
# paqet-socks-watchdog — periodic health check for a SOCKS proxy.
# Runs the recovery command after FAIL_THRESHOLD consecutive failures.
# Generated by install-socks-watchdog.sh; edit via re-running that, not
# by hand (changes will be overwritten on next install).
#
set -uo pipefail

SOCKS_HOST="$SOCKS_HOST"
SOCKS_PORT="$SOCKS_PORT"
CHECK_URL="$CHECK_URL"
FAIL_THRESHOLD="$FAIL_THRESHOLD"
CONNECT_TIMEOUT="$CONNECT_TIMEOUT"
MAX_TIME="$MAX_TIME"
STATE_FILE="$STATE_FILE"
RECOVERY_CMD=$(printf '%q' "$RECOVERY_CMD")

ts() { date -u '+%Y-%m-%dT%H:%M:%SZ'; }

mkdir -p "\$(dirname "\$STATE_FILE")"
fail_count=0
[[ -f "\$STATE_FILE" ]] && fail_count=\$(cat "\$STATE_FILE" 2>/dev/null || echo 0)

# socks5h:// means hostname resolution happens on the proxy side —
# matches how a real client uses paqet to tunnel DNS through too.
# -o /dev/null discards body; -s silences progress; -S still surfaces
# errors. Treat HTTP 4xx as 'proxy worked but target said no' which is
# still proof the SOCKS path is healthy — only TLS/connect errors count
# as a SOCKS failure. So we accept any HTTP response code.
if curl -sS --proxy "socks5h://\$SOCKS_HOST:\$SOCKS_PORT" \\
        --connect-timeout "\$CONNECT_TIMEOUT" --max-time "\$MAX_TIME" \\
        -o /dev/null -w '%{http_code}' "\$CHECK_URL" >/dev/null 2>&1; then
  if (( fail_count > 0 )); then
    echo "\$(ts) paqet-socks-watchdog: recovered after \$fail_count consecutive failures"
  fi
  echo 0 > "\$STATE_FILE"
  exit 0
fi

# Failure path.
fail_count=\$(( fail_count + 1 ))
echo "\$fail_count" > "\$STATE_FILE"
echo "\$(ts) paqet-socks-watchdog: SOCKS \$SOCKS_HOST:\$SOCKS_PORT → \$CHECK_URL failed (\$fail_count/\$FAIL_THRESHOLD)"

if (( fail_count >= FAIL_THRESHOLD )); then
  echo "\$(ts) paqet-socks-watchdog: threshold reached, running recovery: \$RECOVERY_CMD"
  # eval so RECOVERY_CMD can be a full shell command, not just a single
  # binary path. Reset the counter so the next failure starts a new
  # threshold cycle.
  eval "\$RECOVERY_CMD" && rc=0 || rc=\$?
  echo "\$(ts) paqet-socks-watchdog: recovery exited \$rc"
  echo 0 > "\$STATE_FILE"
fi
EOF
  chmod 755 "$SCRIPT_PATH"
}

# ---------------------------------------------------------------------------
# Step 2: write the systemd service + timer
# ---------------------------------------------------------------------------
write_unit_files() {
  log "writing systemd service to $SERVICE_PATH"
  cat > "$SERVICE_PATH" <<EOF
[Unit]
Description=paqet SOCKS proxy watchdog — checks SOCKS5 reachability via curl
Documentation=https://github.com/gitpoemer/paqet/blob/optimize/install-socks-watchdog.sh

[Service]
Type=oneshot
ExecStart=$SCRIPT_PATH
# Output goes to journalctl -u paqet-socks-watchdog.service
StandardOutput=journal
StandardError=journal
# Drop privileges — we only need curl + systemctl restart. Skip if
# the recovery command needs other capabilities.
# (Commented out by default; the script runs as root by design so
#  RECOVERY_CMD='systemctl restart …' works without a sudoers rule.)
#User=nobody
EOF

  log "writing systemd timer to $TIMER_PATH (interval: $CHECK_INTERVAL)"
  cat > "$TIMER_PATH" <<EOF
[Unit]
Description=Periodically run paqet SOCKS watchdog
Requires=paqet-socks-watchdog.service

[Timer]
# First check ${CHECK_INTERVAL} after boot, then every ${CHECK_INTERVAL}.
OnBootSec=${CHECK_INTERVAL}
OnUnitActiveSec=${CHECK_INTERVAL}
AccuracySec=15s
Unit=paqet-socks-watchdog.service

[Install]
WantedBy=timers.target
EOF
}

# ---------------------------------------------------------------------------
# Step 3: reload systemd + (re)enable timer
# ---------------------------------------------------------------------------
activate() {
  log "reloading systemd and enabling the timer"
  systemctl daemon-reload
  systemctl enable --now paqet-socks-watchdog.timer
  systemctl restart paqet-socks-watchdog.timer  # picks up timer changes
}

# ---------------------------------------------------------------------------
# Step 4: friendly summary
# ---------------------------------------------------------------------------
summary() {
  cat <<EOF

================================================================
  Installed paqet-socks-watchdog. Active configuration:
   SOCKS upstream      $SOCKS_HOST:$SOCKS_PORT
   Check URL           $CHECK_URL
   Check interval      $CHECK_INTERVAL  (first run $CHECK_INTERVAL after boot)
   Fail threshold      $FAIL_THRESHOLD  consecutive failures → recovery
   Curl timeouts       connect=${CONNECT_TIMEOUT}s, total=${MAX_TIME}s
   Recovery command    $RECOVERY_CMD
   State file          $STATE_FILE

  Verify next fire time:
    systemctl list-timers paqet-socks-watchdog.timer

  Trigger a one-shot check now (does NOT affect schedule):
    sudo systemctl start paqet-socks-watchdog.service

  Watch the watchdog's logs live:
    journalctl -u paqet-socks-watchdog.service -f

  Reset the failure counter manually:
    sudo bash -c 'echo 0 > $STATE_FILE'

  Uninstall:
    sudo systemctl disable --now paqet-socks-watchdog.timer
    sudo rm -f $SERVICE_PATH $TIMER_PATH $SCRIPT_PATH
    sudo rm -rf $STATE_DIR
    sudo systemctl daemon-reload
================================================================

EOF
}

# ---------------------------------------------------------------------------
# Driver
# ---------------------------------------------------------------------------
main() {
  require_root
  require_cmd curl
  require_cmd systemctl
  write_check_script
  write_unit_files
  activate
  summary
}

main "$@"
